### ISSUE TITLE
Bottom row does not fully draw in landscape mode

### ISSUE THREAD

**Issue by quadroli** [sosauce/CuteCalc#21]
The numbers in the bottom row appear to be 4/5 drawn in landscape mode

Also the 1st and 2nd row buttons appear to be bigger than the 3rd's in landscape mode possibly leading to the 3rd row not having enough space

![Screenshot_20240124_184851](https://github.com/sosauce/CuteCalc/assets/58091631/427809e9-aaca-4e5f-a054-e25063cb345e)

**Comment by sosauce** [comment]
Man i'm never gonna get landscape right 😭... Well imma fix that

**Comment by realeatham** [comment]
I'd say to make the numbers in a numpad formation because 2 rows of numbers like that feels weird to type on. 

Heres an example of what you definitely should not do,  there's way too much empty space between the buttons. Samsung calculator is so bad the entire app can be an example of what not to do. 
![Screenshot_20240125_103824_Calculator](https://github.com/sosauce/CuteCalc/assets/136866675/704430bb-edfe-4226-9fd3-f20d848b2c5a)

**Comment by quadroli** [comment]
😅 unfortunately the issue still persists in 2.4

![Screenshot_20240126_090631](https://github.com/sosauce/CuteCalc/assets/58091631/27110b79-453a-4e9a-a5aa-ef94aa9cd450)

**Comment by sosauce** [comment]
I think how to fix it, will try

**Comment by quadroli** [comment]
I can confirm, fixed in 2.5 🥳
![Screenshot_20240128_125129](https://github.com/sosauce/CuteCalc/assets/58091631/de4d526f-a023-42b7-a478-3ba7e8e6582c)

**Comment by sosauce** [comment]
Yay ! 🥳
