### ISSUE TITLE
Fonts lisence?

### ISSUE THREAD

**Issue by Artem13327** [sosauce/CuteCalc#69]
As I see your application contains custom fonts, so I have a question about the licenses of this fonts.

**Comment by sosauce** [comment]
Hello, it's a font called Nunito, avaible for free here : https://fonts.google.com/specimen/Nunito

**Comment by sosauce** [comment]
Why ? It is stated on Google Fonts : 

**You can use them in your products & projects – print or digital, commercial or otherwise.**

**Comment by sosauce** [comment]
mhmmm, I'll add a text file then

**Comment by notKamui** [comment]
> 2) Original or Modified Versions of the Font Software may be bundled,
redistributed and/or sold with any software, provided that each copy
contains the above copyright notice and this license. These can be
included either as stand-alone text files, human-readable headers or
in the appropriate machine-readable metadata fields within text or
binary files as long as those fields can be easily viewed by the user.

You simply need to download this license file, put in in your repository, and mention in the README that you're using Nunito under the SIL, under free personal non-commercial use.

**Comment by notKamui** [comment]
https://openfontlicense.org/how-to-use-ofl-fonts/

<img width="1092" alt="Screenshot 2024-08-22 at 2 56 28 AM" src="https://github.com/user-attachments/assets/73902a63-3d01-43ea-808f-b399a3c1a714">

See, technically, because you have the font files in your repo, you are technically redistributing the fonts. This is perfectly allowed, but you do need to also have the SIL OFL license file somewhere in your repo

**Comment by sosauce** [comment]
Re-open if needed

**Comment by sosauce** [comment]
Okay 👍
